#!/sbin/busybox sh

if [ "a$3" == "a" ];then
  evalcmd='eval "echo \$GPUTHRESHOLD$2"'
  eval $evalcmd
else
  evalcmd='eval "GPUTHRESHOLD$2=$3"'
  eval $evalcmd
  evalcmd='eval "echo \$GPUTHRESHOLD$2"'
  eval $evalcmd
  echo "$GPUFREQ1 $GPUFREQ2 $GPUFREQ3 $GPUFREQ4 $GPUFREQ5 ${GPUTHRESHOLD1UP}% ${GPUTHRESHOLD2DOWN}% ${GPUTHRESHOLD2UP}% ${GPUTHRESHOLD3DOWN}% ${GPUTHRESHOLD3UP}% ${GPUTHRESHOLD4DOWN}% ${GPUTHRESHOLD4UP}% ${GPUTHRESHOLD5DOWN}%" > /sys/class/misc/gpu_control/gpu_clock_control
fi
